---
- hosts: localhost
  tasks:
  - name: Check Hola
    command: grep -Fxq "hola" /tmp/prueba/prueba.txt
    register: checkmyconf
    check_mode: no
    ignore_errors: yes
    changed_when: no

  - name: Greet Hola in /tmp/prueba/prueba.txt contains "Hola"
    fail: msg="Error"
    when: checkmyconf.rc != 0
