---
- hosts: all
  tasks:  
  - name: Block post checks
    block: 
      - name: read the passwd file
        shell: cat /tmp/prueba/prueba.txt
        register: get_text

      - name: check text exists
        when: get_text.stdout.find('Hola') != -1
        debug: msg="message exists"

      - name: Greet Hola in /tmp/prueba/prueba.txt contains "Hola"
        fail: msg="Error"
        when: get_text.stdout.find('Hola') == -1
      
    always:
      - name: Delete content & directory
        file:
          state: absent
          path: /tmp/prueba/
      
